language: php

php:
  - '7.2'

env:
  global:
    - MODULE_NAME='marvel'
    - SIMPLETEST_BASE_URL='http://localhost'

mysql:
  database: drupal
  username: root
  encoding: utf8

addons:
  hosts:
    - travis.mmenavas.site

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

install:
  # Download and install Drupal Composer.
  - cd .. && composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  - cd drupal && composer install

  # Create symlink to add Marvel module to drupal site.
  - ln -s $TRAVIS_BUILD_DIR web/modules/$MODULE_NAME

  # Install Drupal via `drush si`
  - ./vendor/bin/drush --yes site-install standard --db-url="mysql://root@127.0.0.1/drupal"

  # Enable Marvel module
  - ./vendor/bin/drush en $MODULE_NAME

  - cd web && ../vendor/bin/phpunit -c core/phpunit.xml.dist modules/$MODULE_NAME
